sudo: required
services:
  - docker

before_install:
  - docker build -t lucadefra92/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true lucadefra92/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "docker-react"
  env: "Docker-react-env"
  bucke_name: "elasticbeanstalk-eu-north-1-108156832047"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
